// prisma/seed.js
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const sample = [
    {
      email: 'contact@windycitygrowth.com',
      businessName: 'Windy City Growth',
      slug: 'windy-city-growth',
      expertType: 'agency',
      tagline: 'Meta + Google Ads for local',
      city: 'Chicago',
      state: 'IL',
      rating: 4.7,
      verified: true,
      logo: 'https://placehold.co/80x80',
      services: [
        'seo',
        'ads',
        'social',
        'paid-ads',
        'google-ads',
        'paid-search',
        'ppc',
        'lead-generation',
        'conversion-tracking',
        'meta-ads',
        'facebook-ads',
        'instagram-ads',
        'local-seo',
        'landing-pages',
        'cro',
      ],
      shortDescription: 'Performance marketing for local services.',
      overview: 'We help local businesses grow with a mix of paid media, SEO, and landing page optimization.',
      websiteUrl: 'https://windycitygrowth.com',
      phone: '(312) 555-0188',
      linkedinUrl: 'https://linkedin.com/company/windy-city-growth',
      instagramUrl: 'https://instagram.com/windycitygrowth',
      facebookUrl: 'https://facebook.com/windycitygrowth',
      foundedYear: 2016,
      hourlyRateMin: 85,
      hourlyRateMax: 145,
      minProjectBudget: 5000,
      currencyCode: 'USD',
      languages: ['english', 'spanish'],
      industries: ['home-services', 'healthcare'],
      clientSizes: ['smb', 'mid-market'],
      specialties: ['lead gen', 'conversion rate'],
      remoteFriendly: true,
      servesNationwide: true,
      responseTimeHours: 24,
      featured: true,
      completionScore: 82,
      projects: [
        {
          title: 'Regional clinic paid search rebuild',
          summary: 'Rebuilt fragmented Google Ads campaigns into a single conversion-focused account.',
          challenge: 'Lead volume was flat and campaign structure made reporting unreliable.',
          solution: 'Consolidated campaigns, rewrote landing pages, and introduced call tracking.',
          results: 'Qualified leads increased by 38% in 90 days while cost per lead dropped by 21%.',
          services: ['ads', 'paid-ads', 'google-ads', 'paid-search', 'lead-generation', 'conversion-tracking', 'landing-pages', 'seo'],
          projectBudget: 18000,
          startedAt: '2025-01-15',
          completedAt: '2025-04-15',
          isFeatured: true,
          coverImageUrl: 'https://placehold.co/1200x700?text=Clinic+Growth',
        },
      ],
      clients: [
        {
          name: 'Northside Dental Group',
          logoUrl: 'https://placehold.co/120x120?text=ND',
          websiteUrl: 'https://example.com/northside-dental',
          isFeatured: true,
        },
      ],
      media: [
        {
          type: 'cover',
          url: 'https://placehold.co/1200x700?text=Windy+City+Growth+Cover',
          altText: 'Campaign dashboard overview for Windy City Growth',
        },
        {
          type: 'gallery',
          url: 'https://windycitygrowth.com',
          altText: 'Windy City Growth website preview',
        },
        {
          type: 'video',
          url: 'https://www.instagram.com/p/CQs3bJGImp_/',
          altText: 'Sample public Instagram post used as visible proof on the profile page',
        },
        {
          type: 'video',
          url: 'https://www.instagram.com/p/Cn0Ru6uPJuX/',
          altText: 'Sample public Instagram reel used as visible proof on the profile page',
        },
        {
          type: 'video',
          url: 'https://www.instagram.com/p/C-dfz2ZpBpv/',
          altText: 'Second sample public Instagram reel used as visible proof on the profile page',
        },
      ],
      certifications: [
        {
          title: 'Google Ads Search Certification',
          issuer: 'Google',
          year: 2025,
          url: 'https://skillshop.credential.net/',
          badgeImageUrl: 'https://placehold.co/120x120?text=Google',
        },
        {
          title: 'Meta Certified Media Buying Professional',
          issuer: 'Meta',
          year: 2024,
          url: 'https://www.facebook.com/business/learn/certification',
          badgeImageUrl: 'https://placehold.co/120x120?text=Meta',
        },
      ],
      awards: [
        {
          title: 'Top Local Paid Media Partner',
          issuer: 'Chicago Growth Awards',
          year: 2025,
          url: 'https://example.com/chicago-growth-awards',
          badgeImageUrl: 'https://placehold.co/120x120?text=Award',
        },
      ],
    },
    {
      email: 'hello@napervilledigitalboost.com',
      businessName: 'Naperville Digital Boost',
      slug: 'naperville-digital-boost',
      expertType: 'freelancer',
      tagline: 'SEO & content that compounds',
      city: 'Naperville',
      state: 'IL',
      rating: 4.5,
      verified: false,
      logo: 'https://placehold.co/80x80',
      services: ['seo', 'content', 'local-seo', 'content-seo', 'google-business-profile', 'citations', 'blog-writing', 'seo-content', 'website-copy'],
      shortDescription: 'SEO and content for long-term growth.',
      overview: 'We build sustainable SEO programs focused on content, technical fixes, and local visibility.',
      websiteUrl: 'https://napervilledigitalboost.com',
      phone: '(630) 555-0134',
      linkedinUrl: 'https://linkedin.com/company/naperville-digital-boost',
      instagramUrl: 'https://instagram.com/napervilledigitalboost',
      facebookUrl: 'https://facebook.com/napervilledigitalboost',
      foundedYear: 2019,
      hourlyRateMin: 70,
      hourlyRateMax: 120,
      minProjectBudget: 3000,
      currencyCode: 'USD',
      languages: ['english'],
      industries: ['retail', 'professional-services'],
      clientSizes: ['smb'],
      specialties: ['local seo', 'content marketing'],
      remoteFriendly: true,
      servesNationwide: false,
      responseTimeHours: 36,
      featured: false,
      completionScore: 68,
      projects: [
        {
          title: 'Local SEO relaunch for suburban retailer',
          summary: 'Built a location-led content plan and fixed technical issues blocking map visibility.',
          challenge: 'The site had duplicate local pages and weak rankings outside branded searches.',
          solution: 'Reworked city pages, improved internal linking, and expanded review capture.',
          results: 'Non-branded local clicks grew 52% over two quarters.',
          services: ['seo', 'local-seo', 'content-seo', 'google-business-profile', 'citations', 'blog-writing', 'seo-content', 'website-copy'],
          projectBudget: 9000,
          startedAt: '2025-02-01',
          completedAt: '2025-07-01',
          isFeatured: true,
          coverImageUrl: 'https://placehold.co/1200x700?text=SEO+Relaunch',
        },
      ],
      clients: [
        {
          name: 'Downtown Home & Patio',
          logoUrl: 'https://placehold.co/120x120?text=DH',
          websiteUrl: 'https://example.com/downtown-home-patio',
          isFeatured: true,
        },
      ],
      media: [
        {
          type: 'gallery',
          url: 'https://placehold.co/1000x700?text=SEO+Content+Hub',
          altText: 'SEO content hub design and navigation example',
        },
        {
          type: 'video',
          url: 'https://www.instagram.com/napervilledigitalboost/',
          altText: 'Naperville Digital Boost Instagram profile',
        },
      ],
      certifications: [
        {
          title: 'Google Analytics Certification',
          issuer: 'Google',
          year: 2025,
          url: 'https://skillshop.credential.net/',
          badgeImageUrl: 'https://placehold.co/120x120?text=GA4',
        },
      ],
      awards: [],
    },
    {
      email: 'team@evanstonsociallab.com',
      businessName: 'Evanston Social Lab',
      slug: 'evanston-social-lab',
      expertType: 'creator',
      tagline: 'Short-form video + socials',
      city: 'Evanston',
      state: 'IL',
      rating: 4.2,
      verified: true,
      logo: 'https://placehold.co/80x80',
      services: [
        'social',
        'video',
        'creator-marketing',
        'local-influencer',
        'instagram-creator',
        'tiktok-creator',
        'sponsored-post',
        'creator-visit',
        'ugc',
        'creator-content',
        'short-form-video',
        'instagram-reels',
        'video-production',
        'video-editing',
        'reels-production',
        'reels-editing',
      ],
      shortDescription: 'Short-form social content that converts.',
      overview: 'We plan, shoot, and edit reels plus run paid social to grow your audience.',
      websiteUrl: 'https://evanstonsociallab.com',
      phone: '(847) 555-0199',
      linkedinUrl: 'https://linkedin.com/company/evanston-social-lab',
      instagramUrl: 'https://instagram.com/evanstonsociallab',
      facebookUrl: 'https://facebook.com/evanstonsociallab',
      creatorPlatforms: ['instagram', 'tiktok', 'youtube'],
      creatorAudienceSize: 185000,
      creatorProofSummary: 'Audience built through hospitality and retail creator campaigns with repeat local brand sponsorships.',
      foundedYear: 2018,
      hourlyRateMin: 90,
      hourlyRateMax: 160,
      minProjectBudget: 6000,
      currencyCode: 'USD',
      languages: ['english'],
      industries: ['hospitality', 'retail'],
      clientSizes: ['smb', 'mid-market'],
      specialties: ['video production', 'paid social'],
      remoteFriendly: false,
      servesNationwide: true,
      responseTimeHours: 18,
      featured: true,
      completionScore: 77,
      projects: [
        {
          title: 'Restaurant reels and paid social sprint',
          summary: 'Produced a month-long short-form video campaign around new menu launches.',
          challenge: 'The brand had strong walk-in traffic but weak repeat engagement on social.',
          solution: 'Delivered weekly reels, creator-style edits, and promotion-based paid social targeting.',
          results: 'Follower growth doubled and promoted offers drove a 27% lift in tracked redemptions.',
          services: ['social', 'creator-marketing', 'ugc', 'short-form-video', 'instagram-reels', 'video-production', 'video-editing', 'reels-production'],
          projectBudget: 14000,
          startedAt: '2025-03-10',
          completedAt: '2025-05-20',
          isFeatured: true,
          coverImageUrl: 'https://placehold.co/1200x700?text=Restaurant+Reels',
        },
      ],
      clients: [
        {
          name: 'Lakefront Bistro',
          logoUrl: 'https://placehold.co/120x120?text=LB',
          websiteUrl: 'https://example.com/lakefront-bistro',
          isFeatured: true,
        },
      ],
      media: [
        {
          type: 'video',
          url: 'https://www.instagram.com/evanstonsociallab/',
          altText: 'Evanston Social Lab Instagram profile',
        },
        {
          type: 'gallery',
          url: 'https://placehold.co/1000x700?text=Storyboard+Frames',
          altText: 'Storyboard frames from a social video shoot',
        },
      ],
      certifications: [
        {
          title: 'Meta Certified Creative Strategy Professional',
          issuer: 'Meta',
          year: 2024,
          url: 'https://www.facebook.com/business/learn/certification',
          badgeImageUrl: 'https://placehold.co/120x120?text=Meta',
        },
      ],
      awards: [
        {
          title: 'Best Social Campaign Concept',
          issuer: 'North Shore Marketing Awards',
          year: 2025,
          url: 'https://example.com/north-shore-awards',
          badgeImageUrl: 'https://placehold.co/120x120?text=NS',
        },
      ],
    },
    {
      email: 'print@oakparkprintco.com',
      businessName: 'Oak Park Print Co.',
      slug: 'oak-park-print-co',
      expertType: 'specialist',
      tagline: 'Flyers, menus, window wraps',
      city: 'Oak Park',
      state: 'IL',
      rating: 4.0,
      verified: false,
      logo: 'https://placehold.co/80x80',
      services: ['print', 'branding', 'print-design', 'flyers', 'menus', 'brand-identity', 'social-templates'],
      shortDescription: 'Print design and production for local brands.',
      overview: 'We handle design, layout, and fast print turnaround for restaurants and shops.',
      websiteUrl: 'https://oakparkprintco.com',
      phone: '(708) 555-0121',
      linkedinUrl: 'https://linkedin.com/company/oak-park-print-co',
      instagramUrl: 'https://instagram.com/oakparkprintco',
      facebookUrl: 'https://facebook.com/oakparkprintco',
      foundedYear: 2012,
      hourlyRateMin: 60,
      hourlyRateMax: 110,
      minProjectBudget: 1500,
      currencyCode: 'USD',
      languages: ['english'],
      industries: ['restaurant', 'retail'],
      clientSizes: ['smb'],
      specialties: ['print design', 'brand collateral'],
      remoteFriendly: false,
      servesNationwide: false,
      responseTimeHours: 48,
      featured: false,
      completionScore: 61,
      projects: [
        {
          title: 'Restaurant print collateral refresh',
          summary: 'Refreshed menus, storefront posters, and takeout inserts for a neighborhood group.',
          challenge: 'Brand materials were inconsistent across locations and seasonal offers were slow to launch.',
          solution: 'Created reusable templates and a faster approval workflow for print production.',
          results: 'Turnaround time for new promotions dropped from two weeks to four days.',
          services: ['print', 'print-design', 'menus', 'flyers', 'branding', 'brand-identity'],
          projectBudget: 4500,
          startedAt: '2025-01-05',
          completedAt: '2025-02-14',
          isFeatured: false,
          coverImageUrl: 'https://placehold.co/1200x700?text=Print+Collateral',
        },
      ],
      clients: [
        {
          name: 'Union Pizza House',
          logoUrl: 'https://placehold.co/120x120?text=UP',
          websiteUrl: 'https://example.com/union-pizza-house',
          isFeatured: true,
        },
      ],
      media: [
        {
          type: 'gallery',
          url: 'https://placehold.co/1000x700?text=Menu+Suite',
          altText: 'Printed menu suite and window poster set',
        },
        {
          type: 'video',
          url: 'https://www.instagram.com/oakparkprintco/',
          altText: 'Oak Park Print Co. Instagram profile',
        },
      ],
      certifications: [],
      awards: [],
    },
    {
      email: 'hello@riversidereputationpartners.com',
      businessName: 'Riverside Reputation Partners',
      slug: 'riverside-reputation-partners',
      expertType: 'specialist',
      tagline: 'Reviews, trust, and local reputation',
      city: 'Hinsdale',
      state: 'IL',
      rating: 4.6,
      verified: true,
      logo: 'https://placehold.co/80x80',
      services: ['reviews', 'google-reviews', 'reputation-management', 'review-management', 'testimonials', 'trust-building', 'local-seo', 'seo'],
      shortDescription: 'Review growth and reputation systems for local service businesses.',
      overview: 'We help businesses collect better reviews, tighten trust signals, and recover from weak local reputation patterns.',
      websiteUrl: 'https://riversidereputationpartners.com',
      phone: '(630) 555-0177',
      linkedinUrl: 'https://linkedin.com/company/riverside-reputation-partners',
      instagramUrl: 'https://instagram.com/riversidereputationpartners',
      facebookUrl: 'https://facebook.com/riversidereputationpartners',
      foundedYear: 2020,
      hourlyRateMin: 80,
      hourlyRateMax: 130,
      minProjectBudget: 2500,
      currencyCode: 'USD',
      languages: ['english'],
      industries: ['healthcare', 'professional-services', 'home-services'],
      clientSizes: ['smb'],
      specialties: ['review generation', 'trust building'],
      remoteFriendly: true,
      servesNationwide: false,
      responseTimeHours: 24,
      featured: false,
      completionScore: 73,
      projects: [
        {
          title: 'Reputation recovery for suburban clinic group',
          summary: 'Rebuilt the review capture flow and fixed inconsistent listings after a rough patient feedback cycle.',
          challenge: 'The clinic had strong patient outcomes but weak review volume and inconsistent trust signals across Google.',
          solution: 'Created a review request system, improved response handling, and refreshed key trust elements on the listing and site.',
          results: 'Google review volume tripled in 4 months and average rating improved from 3.9 to 4.5.',
          services: ['reviews', 'google-reviews', 'reputation-management', 'review-management', 'trust-building'],
          projectBudget: 6200,
          startedAt: '2025-02-03',
          completedAt: '2025-06-12',
          isFeatured: true,
          coverImageUrl: 'https://placehold.co/1200x700?text=Reputation+Recovery',
        },
      ],
      clients: [
        {
          name: 'Prairie Family Clinic',
          logoUrl: 'https://placehold.co/120x120?text=PFC',
          websiteUrl: 'https://example.com/prairie-family-clinic',
          isFeatured: true,
        },
      ],
      media: [
        {
          type: 'gallery',
          url: 'https://placehold.co/1000x700?text=Review+System',
          altText: 'Review request system dashboard and rating lift summary',
        },
      ],
      certifications: [],
      awards: [],
    },
    {
      email: 'team@shopfrontgrowthstudio.com',
      businessName: 'Shopfront Growth Studio',
      slug: 'shopfront-growth-studio',
      expertType: 'agency',
      tagline: 'Shopify growth for local product brands',
      city: 'Chicago',
      state: 'IL',
      rating: 4.8,
      verified: true,
      logo: 'https://placehold.co/80x80',
      services: ['ads', 'email', 'web', 'ecommerce-marketing', 'shopify-marketing', 'shopping-ads', 'product-pages', 'email-marketing', 'affiliate-marketing'],
      shortDescription: 'Ecommerce growth for product brands that need better ads, pages, and retention.',
      overview: 'We help product businesses tighten their storefront, paid acquisition, and repeat-purchase systems across Shopify and email.',
      websiteUrl: 'https://shopfrontgrowthstudio.com',
      phone: '(312) 555-0162',
      linkedinUrl: 'https://linkedin.com/company/shopfront-growth-studio',
      instagramUrl: 'https://instagram.com/shopfrontgrowthstudio',
      facebookUrl: 'https://facebook.com/shopfrontgrowthstudio',
      foundedYear: 2017,
      hourlyRateMin: 95,
      hourlyRateMax: 165,
      minProjectBudget: 7000,
      currencyCode: 'USD',
      languages: ['english'],
      industries: ['retail', 'events'],
      clientSizes: ['smb', 'mid-market'],
      specialties: ['shopify growth', 'shopping ads', 'retention'],
      remoteFriendly: true,
      servesNationwide: true,
      responseTimeHours: 20,
      featured: true,
      completionScore: 84,
      projects: [
        {
          title: 'Shopify growth sprint for a local gift brand',
          summary: 'Improved product pages, launched shopping ads, and added retention email flows.',
          challenge: 'Traffic existed, but conversion rates and repeat purchases were too weak to support ad spend.',
          solution: 'Rebuilt product page structure, launched shopping campaigns, and introduced browse/cart recovery plus post-purchase email.',
          results: 'Online revenue grew 41% over one quarter and repeat customer rate improved by 18%.',
          services: ['ecommerce-marketing', 'shopify-marketing', 'shopping-ads', 'product-pages', 'email-marketing', 'ads', 'email', 'web'],
          projectBudget: 22000,
          startedAt: '2025-01-20',
          completedAt: '2025-05-01',
          isFeatured: true,
          coverImageUrl: 'https://placehold.co/1200x700?text=Shopify+Growth',
        },
      ],
      clients: [
        {
          name: 'Oak Street Goods',
          logoUrl: 'https://placehold.co/120x120?text=OS',
          websiteUrl: 'https://example.com/oak-street-goods',
          isFeatured: true,
        },
      ],
      media: [
        {
          type: 'gallery',
          url: 'https://placehold.co/1000x700?text=Shopify+Dashboard',
          altText: 'Shopify growth dashboard and product page examples',
        },
      ],
      certifications: [],
      awards: [],
    },
    {
      email: 'hello@mainstreetgrowthadvisory.com',
      businessName: 'Main Street Growth Advisory',
      slug: 'main-street-growth-advisory',
      expertType: 'freelancer',
      tagline: 'Strategy before spend',
      city: 'Downers Grove',
      state: 'IL',
      rating: 4.4,
      verified: true,
      logo: 'https://placehold.co/80x80',
      services: ['marketing-strategy', 'marketing-audit', 'growth-strategy', 'analytics', 'ga4', 'reporting', 'consulting'],
      shortDescription: 'Marketing strategy, audits, and reporting for owners who need a clearer plan.',
      overview: 'We help business owners figure out what to fix first before hiring a full channel team or increasing budget.',
      websiteUrl: 'https://mainstreetgrowthadvisory.com',
      phone: '(630) 555-0148',
      linkedinUrl: 'https://linkedin.com/company/main-street-growth-advisory',
      instagramUrl: 'https://instagram.com/mainstreetgrowthadvisory',
      facebookUrl: 'https://facebook.com/mainstreetgrowthadvisory',
      foundedYear: 2021,
      hourlyRateMin: 110,
      hourlyRateMax: 180,
      minProjectBudget: 3500,
      currencyCode: 'USD',
      languages: ['english'],
      industries: ['professional-services', 'education', 'home-services'],
      clientSizes: ['smb'],
      specialties: ['marketing audits', 'measurement', 'growth planning'],
      remoteFriendly: true,
      servesNationwide: true,
      responseTimeHours: 30,
      featured: false,
      completionScore: 71,
      projects: [
        {
          title: 'Growth roadmap for multi-location home service brand',
          summary: 'Delivered a channel audit, reporting cleanup, and clear six-month marketing roadmap.',
          challenge: 'The owner had multiple vendors but no usable view of what was actually driving calls.',
          solution: 'Audited the stack, fixed reporting assumptions, and mapped the next six months around demand and trust priorities.',
          results: 'Leadership cut wasted spend, aligned vendors around one plan, and reduced reporting time by 60%.',
          services: ['marketing-strategy', 'marketing-audit', 'growth-strategy', 'analytics', 'ga4', 'reporting', 'consulting'],
          projectBudget: 9800,
          startedAt: '2025-03-04',
          completedAt: '2025-04-22',
          isFeatured: true,
          coverImageUrl: 'https://placehold.co/1200x700?text=Growth+Roadmap',
        },
      ],
      clients: [
        {
          name: 'Evergreen Home Pros',
          logoUrl: 'https://placehold.co/120x120?text=EH',
          websiteUrl: 'https://example.com/evergreen-home-pros',
          isFeatured: true,
        },
      ],
      media: [
        {
          type: 'gallery',
          url: 'https://placehold.co/1000x700?text=Strategy+Roadmap',
          altText: 'Strategy roadmap and reporting dashboard preview',
        },
      ],
      certifications: [],
      awards: [],
    },
  ];

  for (const expertSeed of sample) {
    const { projects = [], clients = [], media = [], reviews = [], certifications = [], awards = [], ...expertData } = expertSeed;

    const expert = await prisma.expert.upsert({
      where: { slug: expertSeed.slug },
      update: expertData,
      create: expertData,
    });

    await prisma.expertProject.deleteMany({ where: { expertId: expert.id } });
    await prisma.expertClient.deleteMany({ where: { expertId: expert.id } });
    await prisma.expertMedia.deleteMany({ where: { expertId: expert.id } });
    await prisma.expertReview.deleteMany({ where: { expertId: expert.id } });
    await prisma.expertCertification.deleteMany({ where: { expertId: expert.id } });
    await prisma.expertAward.deleteMany({ where: { expertId: expert.id } });

    if (projects.length) {
      await prisma.expertProject.createMany({
        data: projects.map((project, index) => ({
          expertId: expert.id,
          title: project.title,
          summary: project.summary,
          challenge: project.challenge,
          solution: project.solution,
          results: project.results,
          services: project.services || [],
          projectBudget: project.projectBudget ?? null,
          startedAt: project.startedAt ? new Date(project.startedAt) : null,
          completedAt: project.completedAt ? new Date(project.completedAt) : null,
          isFeatured: Boolean(project.isFeatured),
          coverImageUrl: project.coverImageUrl ?? null,
          sortOrder: index,
        })),
      });
    }

    if (clients.length) {
      await prisma.expertClient.createMany({
        data: clients.map((client, index) => ({
          expertId: expert.id,
          name: client.name,
          logoUrl: client.logoUrl ?? null,
          websiteUrl: client.websiteUrl ?? null,
          isFeatured: Boolean(client.isFeatured),
          sortOrder: index,
        })),
      });
    }

    if (media.length) {
      await prisma.expertMedia.createMany({
        data: media.map((item, index) => ({
          expertId: expert.id,
          type: item.type,
          url: item.url,
          altText: item.altText ?? null,
          sortOrder: index,
        })),
      });
    }

    if (reviews.length) {
      await prisma.expertReview.createMany({
        data: reviews.map((review, index) => ({
          expertId: expert.id,
          reviewerName: review.reviewerName,
          company: review.company ?? null,
          rating: review.rating,
          communicationRating: review.communicationRating ?? null,
          qualityRating: review.qualityRating ?? null,
          valueRating: review.valueRating ?? null,
          title: review.title ?? null,
          body: review.body,
          projectSummary: review.projectSummary ?? null,
          verified: Boolean(review.verified),
          source: review.source ?? null,
          publishedAt: review.publishedAt ? new Date(review.publishedAt) : null,
          sortOrder: index,
        })),
      });
    }

    if (certifications.length) {
      await prisma.expertCertification.createMany({
        data: certifications.map((item, index) => ({
          expertId: expert.id,
          title: item.title,
          issuer: item.issuer,
          year: item.year ?? null,
          url: item.url ?? null,
          badgeImageUrl: item.badgeImageUrl ?? null,
          sortOrder: index,
        })),
      });
    }

    if (awards.length) {
      await prisma.expertAward.createMany({
        data: awards.map((item, index) => ({
          expertId: expert.id,
          title: item.title,
          issuer: item.issuer,
          year: item.year ?? null,
          url: item.url ?? null,
          badgeImageUrl: item.badgeImageUrl ?? null,
          sortOrder: index,
        })),
      });
    }
  }

  console.log(`Seeded ${sample.length} experts`);
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
