// prisma/seed.js
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  const sample = [
    {
      email: "contact@windycitygrowth.com",
      businessName: "Windy City Growth",
      slug: "windy-city-growth",
      tagline: "Meta + Google Ads for local",
      city: "Chicago",
      state: "IL",
      rating: 4.7,
      verified: true,
      logo: "https://placehold.co/80x80",
      services: ["seo", "ads", "social"],
      shortDescription: "Performance marketing for local services.",
      overview: "We help local businesses grow with a mix of paid media, SEO, and landing page optimization.",
      websiteUrl: "https://windycitygrowth.com",
      phone: "(312) 555-0188",
      linkedinUrl: "https://linkedin.com/company/windy-city-growth",
      instagramUrl: "https://instagram.com/windycitygrowth",
      facebookUrl: "https://facebook.com/windycitygrowth",
      foundedYear: 2016,
      hourlyRateMin: 85,
      hourlyRateMax: 145,
      minProjectBudget: 5000,
      currencyCode: "USD",
      languages: ["english", "spanish"],
      industries: ["home-services", "healthcare"],
      clientSizes: ["smb", "mid-market"],
      specialties: ["lead gen", "conversion rate"],
      remoteFriendly: true,
      servesNationwide: true,
      responseTimeHours: 24,
      featured: true,
      completionScore: 82,
    },
    {
      email: "hello@napervilledigitalboost.com",
      businessName: "Naperville Digital Boost",
      slug: "naperville-digital-boost",
      tagline: "SEO & content that compounds",
      city: "Naperville",
      state: "IL",
      rating: 4.5,
      verified: false,
      logo: "https://placehold.co/80x80",
      services: ["seo"],
      shortDescription: "SEO and content for long-term growth.",
      overview: "We build sustainable SEO programs focused on content, technical fixes, and local visibility.",
      websiteUrl: "https://napervilledigitalboost.com",
      phone: "(630) 555-0134",
      linkedinUrl: "https://linkedin.com/company/naperville-digital-boost",
      instagramUrl: "https://instagram.com/napervilledigitalboost",
      facebookUrl: "https://facebook.com/napervilledigitalboost",
      foundedYear: 2019,
      hourlyRateMin: 70,
      hourlyRateMax: 120,
      minProjectBudget: 3000,
      currencyCode: "USD",
      languages: ["english"],
      industries: ["retail", "professional-services"],
      clientSizes: ["smb"],
      specialties: ["local seo", "content marketing"],
      remoteFriendly: true,
      servesNationwide: false,
      responseTimeHours: 36,
      featured: false,
      completionScore: 68,
    },
    {
      email: "team@evanstonsociallab.com",
      businessName: "Evanston Social Lab",
      slug: "evanston-social-lab",
      tagline: "Short-form video + socials",
      city: "Evanston",
      state: "IL",
      rating: 4.2,
      verified: true,
      logo: "https://placehold.co/80x80",
      services: ["social", "video"],
      shortDescription: "Short-form social content that converts.",
      overview: "We plan, shoot, and edit reels plus run paid social to grow your audience.",
      websiteUrl: "https://evanstonsociallab.com",
      phone: "(847) 555-0199",
      linkedinUrl: "https://linkedin.com/company/evanston-social-lab",
      instagramUrl: "https://instagram.com/evanstonsociallab",
      facebookUrl: "https://facebook.com/evanstonsociallab",
      foundedYear: 2018,
      hourlyRateMin: 90,
      hourlyRateMax: 160,
      minProjectBudget: 6000,
      currencyCode: "USD",
      languages: ["english"],
      industries: ["hospitality", "retail"],
      clientSizes: ["smb", "mid-market"],
      specialties: ["video production", "paid social"],
      remoteFriendly: false,
      servesNationwide: true,
      responseTimeHours: 18,
      featured: true,
      completionScore: 77,
    },
    {
      email: "print@oakparkprintco.com",
      businessName: "Oak Park Print Co.",
      slug: "oak-park-print-co",
      tagline: "Flyers, menus, window wraps",
      city: "Oak Park",
      state: "IL",
      rating: 4.0,
      verified: false,
      logo: "https://placehold.co/80x80",
      services: ["print"],
      shortDescription: "Print design and production for local brands.",
      overview: "We handle design, layout, and fast print turnaround for restaurants and shops.",
      websiteUrl: "https://oakparkprintco.com",
      phone: "(708) 555-0121",
      linkedinUrl: "https://linkedin.com/company/oak-park-print-co",
      instagramUrl: "https://instagram.com/oakparkprintco",
      facebookUrl: "https://facebook.com/oakparkprintco",
      foundedYear: 2012,
      hourlyRateMin: 60,
      hourlyRateMax: 110,
      minProjectBudget: 1500,
      currencyCode: "USD",
      languages: ["english"],
      industries: ["restaurant", "retail"],
      clientSizes: ["smb"],
      specialties: ["print design", "brand collateral"],
      remoteFriendly: false,
      servesNationwide: false,
      responseTimeHours: 48,
      featured: false,
      completionScore: 61,
    },
  ];

  for (const p of sample) {
    await prisma.provider.upsert({
      where: { slug: p.slug },
      update: p,
      create: p,
    });
  }

  console.log(`✅ Seeded ${sample.length} providers`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
